name: Fuzz

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-fuzz
      - run: cargo fuzz run analysis -- -max_total_time=60
